name: Deploy to Github Pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.15.1

            - name: Run Install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Build Production build-and-deploy
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: gh-pages
                  folder: build
